import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
df_xy = pd.read_csv('birthweight.csv')
np_bw=df_xy['Birthweight'].to_numpy()
np_ge=df_xy['Gestation'].to_numpy()
np_ma=df_xy['mage'].to_numpy()
np_mn=df_xy['mnocig'].to_numpy()
np_mh=df_xy['mheight'].to_numpy()
np_mp=df_xy['mppwt'].to_numpy()
np_fa=df_xy['fage'].to_numpy()
np_fe=df_xy['fedyrs'].to_numpy()
np_fn=df_xy['fnocig'].to_numpy()
np_fh=df_xy['fheight'].to_numpy()
plt.scatter(np_bw, np_ge)
plt.xlabel("Birthweight")
plt.ylabel('Gestation')
plt.title("Birthweight x Gestation")
plt.show()
plt.scatter(np_bw, np_ma)
plt.xlabel("Birthweight")
plt.ylabel('mage')
plt.title("Birthweight x mage")
plt.show()
plt.scatter(np_bw, np_mn)
plt.xlabel("Birthweight")
plt.ylabel('mnocig')
plt.title("Birthweight x mnocig ")
plt.show()
plt.scatter(np_bw, np_mh)
plt.xlabel("Birthweight")
plt.ylabel('mheight')
plt.title("Birthweight x mheight")
plt.show()
plt.scatter(np_bw, np_mp)
plt.xlabel("Birthweight")
plt.ylabel('mppwt')
plt.title("Birthweight x mppwt ")
plt.show()
plt.scatter(np_bw, np_fa)
plt.xlabel("Birthweight")
plt.ylabel('fage')
plt.title("Birthweight x fage")
plt.show()
plt.scatter(np_bw, np_fe)
plt.xlabel("Birthweight")
plt.ylabel('fedyrs')
plt.title("Birthweight x fedyrs")
plt.show()
plt.scatter(np_bw, np_fn)
plt.xlabel("Birthweight")
plt.ylabel('fnocig')
plt.title("Birthweight x fnocig")
plt.show()
plt.scatter(np_bw, np_fh)
plt.xlabel("Birthweight")
plt.ylabel('fheight')
plt.title("Birthweight x fheight")
plt.show()



